services:
  web3270:
    build: .
    ports:
      - "8080:8080"
    environment:
     # - DEFAULT_SERVER=local1
      - MAINFRAME_USER=HERC01
      - MAINFRAME_PASSWORD=CUL8TR
    depends_on:
      - mvs1
      - mvs2
      - mvs3
      - mvs4

  mvs1:
    image: rattydave/docker-ubuntu-hercules-mvs
    ports:
      - "3271:3270"   # TN3270
      - "8038:8038"   # Hercules web console

  mvs2:
    image: rattydave/docker-ubuntu-hercules-mvs
    ports:
      - "3272:3270"   # TN3270
      - "8039:8038"   # Hercules web console

  mvs3:
    image: rattydave/docker-ubuntu-hercules-mvs
    ports:
      - "3273:3270"   # TN3270
      - "8040:8038"   # Hercules web console

  mvs4:
    image: rattydave/docker-ubuntu-hercules-mvs
    ports:
      - "3274:3270"   # TN3270
      - "8041:8038"   # Hercules web console
